version: '3'

services:
  scoreboard.api:
    image: scoreboard.api
    build:
      context: ./src/CardGames.BeggarMyNeighbour.Scoreboard.API
      dockerfile: Dockerfile
    links:
      - beggareventbus
    ports:
     - "8087:80"
  beggareventbus:
    image: rabbitmq:3.6.10-management
    ports:
     - "8080:15672"

  beggarverify:
    image: beggarverify
    build:
      context: ./src/CardGames.BeggarMyNeighbour.Verify
      dockerfile: Dockerfile
    links:
     - beggareventbus
