// <auto-generated />
using System;
using CardGames.BeggarMyNeighbour.Scoreboard.API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CardGames.BeggarMyNeighbour.Scoreboard.API.Migrations
{
    [DbContext(typeof(ScoreBoardContext))]
    [Migration("20260621000000_AddIteration")]
    partial class AddIteration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CardGames.BeggarMyNeighbour.Scoreboard.Models.Score", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Deck")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstanceId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("Iteration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Players")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Strategy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Submitted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Verified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("Submitted")
                        .HasDatabaseName("IX_Scores_Submitted");

                    b.HasIndex("Deck", "Players")
                        .IsUnique()
                        .HasDatabaseName("IX_Scores_Deck_Players");

                    b.ToTable("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
